---
name: "Linting"

on:
  pull_request:
    branches:
      - main

jobs:
  sh-checker:
    name: "Shell Checker (shellcheck, shfmt, checkbashisms)"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run sh-checker"
        uses: luizm/action-sh-checker@v0.10.0
        with:
          sh_checker_checkbashisms_enable: true

  hadolint:
    name: "Hadolint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run Hadolint"
        uses: hadolint/hadolint-action@v3.3.0

  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run Yamllint"
        uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  actionlint:
    name: "Actionlint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run actionlint"
        uses: reviewdog/action-actionlint@v1.71.0
        with:
          reporter: github-annotations
          fail_level: info

  docker-check:
    name: "Docker Buildx Check"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.31.1
          driver-opts: image=moby/buildkit:v0.27.1

      - name: "Run Buildx Check"
        uses: docker/build-push-action@v6
        with:
          context: .
          call: check
          platforms: linux/amd64,linux/arm64
