name: "Linting"

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: "ShellCheck"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run ShellCheck"
        uses: reviewdog/action-shellcheck@v1.32.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_level: info
          filter_mode: nofilter
          check_all_files_with_shebangs: true

  shfmt:
    name: "shfmt"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run shfmt"
        uses: reviewdog/action-shfmt@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: nofilter

  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run Yamllint"
        uses: reviewdog/action-yamllint@v1.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          filter_mode: nofilter
          fail_level: info
          yamllint_flags: '. -d "{extends: relaxed, rules: {line-length: {max: 120}}}"'

  actionlint:
    name: "Actionlint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run actionlint"
        uses: reviewdog/action-actionlint@v1.71.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_level: info
          filter_mode: nofilter

  hadolint:
    name: "Hadolint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run Hadolint"
        uses: hadolint/hadolint-action@v3.3.0

  docker-build-checks:
    name: "Docker Buildx Checks"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        env:
          DOCKER_BUILDX_VERSION: v0.31.1
          DOCKER_BUILDKIT_VERSION: v0.27.1
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          driver-opts: image=moby/buildkit:${{ env.DOCKER_BUILDKIT_VERSION }}

      - name: "Run Buildx Checks"
        uses: docker/build-push-action@v6
        with:
          context: .
          call: check
          platforms: linux/amd64,linux/arm64
